### ISSUE TITLE
force_network field value invalid error on PayloadClient.CreateAndSubscribeAsync

### ISSUE THREAD

**Issue by JakeLardinois** [XRPL-Labs/XUMM.NET.SDK#40]
Hey, this is a great library and thank you for all your hard work on it!
I am getting an error when adding XummPayloadOptions to the XummPostJsonPayload.Options property.  This is what I am setting:
![image](https://github.com/user-attachments/assets/551f6fc6-066a-45c5-97f1-ee348bb21a1d)

The Xaman Developer Console shows the following error.
![image](https://github.com/user-attachments/assets/3a214a73-9224-4b2f-95f1-b070cd68c9df)

If I comment out the XummPayloadOptions then the execution runs without issue.

**Comment by JakeLardinois** [comment]
I'm using version 1.9.3 of Xumm.Net.Sdk on .NET 8.0

**Comment by DominiqueBlomsma** [comment]
Hi @JakeLardinois , thanks for the compliment and using the library!
Assuming that you don't want to force a network please set `ForceNetwork` to `null` or don't set a value in `XummPayloadOptions` since it's default value is `null`.

Please check out `IXummMiscClient.GetRailsAsync` for valid values if you would like to force a network on a payload.

**Comment by JakeLardinois** [comment]
Ok.  Thank you for the information and quick response @DominiqueBlomsma.  It is much appreciated!!
